development:
  secret_key_base: bikeSpeed
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket_name: <%= ENV["AWS_BUCKET_NAME"] %>
  aws_bucket_region: <%= ENV["AWS_BUCKET_REGION"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket_name: <%= ENV["AWS_BUCKET_NAME"] %>
  aws_bucket_region: <%= ENV["AWS_BUCKET_REGION"] %>
