# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ddb667247f7645233246b28bdcb76bee4562f7f91d6db8ad9af55eb2d84d73897e408168364662ee902af36875d2cd95b648b2cd9ff4fcae0d55dc4a1a0983d
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket_name: <%= ENV["AWS_BUCKET_NAME"] %>
  aws_bucket_region: <%= ENV["AWS_BUCKET_REGION"] %>

test:
  secret_key_base: 5afd6a06ddd2b3ca230060258330c457522064dff88f45db853051265bb97b754836c4798f465679deb8ca061362af31ffc52eae91b1dee0a70bd509ce162498
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket_name: <%= ENV["AWS_BUCKET_NAME"] %>
  aws_bucket_region: <%= ENV["AWS_BUCKET_REGION"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket_name: <%= ENV["AWS_BUCKET_NAME"] %>
  aws_bucket_region: <%= ENV["AWS_BUCKET_REGION"] %>
